import type { Metadata } from "next";

import "./globals.css";
import React from "react";
import localFont from "next/font/local";

const inter = localFont({
    variable: "--font-inter",
    src: "./fonts/InterVF.ttf",
    weight: "100 200 300 400 500 600 700 800 900",
});

const spaceGrotesk = localFont({
    variable: "--font-space-grotesk",
    src: "./fonts/SpaceGroteskVF.ttf",
    weight: "300 400 500 600 700",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.className} ${spaceGrotesk.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
